"""Initial migrations

Revision ID: 5ddc6c823336
Revises: 
Create Date: 2024-02-29 13:50:21.547268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddc6c823336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Item', sa.String(length=20), nullable=False),
    sa.Column('Category', sa.String(length=50), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Units_of_Measurement', sa.String(length=15), nullable=False),
    sa.Column('Unit_Cost', sa.Integer(), nullable=False),
    sa.Column('Supplier', sa.String(length=50), nullable=False),
    sa.Column('Purchase_Date', sa.DateTime(), nullable=True),
    sa.Column('Expiry_Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventories')
    # ### end Alembic commands ###
